services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env.production
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mariadb:10.11
    ports:
      - '${DB_PORT}:3306'
    env_file:
      - .env.production
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mariadb_data_prod:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  mariadb_data_prod:
